version: "3.7"
services:
  adapter-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dev-postgres-db
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: dev-adapter-db

  app:
    build:
      context: .
      dockerfile: Dockerfile.service1
    ports:
      - 3000:3000

  app1:
    build:
      context: .
      dockerfile: Dockerfile.service2
    ports:
      - 3001:3001

  kafka:
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
